# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d09cd4fe6a5f9bf2efa62e9571a31a083d02f375a63ece755149562e811f4f12e956d365177f502a1ca1f1f63c4f79efe0c3ec97c0e3f83005c3e4d68c0312

test:
  secret_key_base: 27bc5dbc04c6fe7aa1afc1b3e30499a6c112e88ebde9bfb1d25d9f9182469bfda3c75589323dc75914f99ec4a14b9556510fa28acbe9c0da24139be576737af1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
